theme: jekyll-theme-minimal
title: pepperkit
description: A kit of unrelated tools for Java developers
logo: https://avatars.githubusercontent.com/u/79530455?s=400&u=d6ad6665123ceb9923f9b25c57617911abb00ffb&v=4
